version: '3.8'

services:
  # Core Infrastructure
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: quantum_banking
      POSTGRES_USER: quantum_user
      POSTGRES_PASSWORD: quantum_secure_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - banking-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis_secure_pass
    ports:
      - "6379:6379"
    networks:
      - banking-network

  # Main Backend API
  backend:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://quantum_user:quantum_secure_pass@postgres:5432/quantum_banking
      - REDIS_URL=redis://:redis_secure_pass@redis:6379/0
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge